### ISSUE TITLE
bug: One run adds cc_proto_library targets, the next one removes them

### ISSUE THREAD

**Issue by satreix** [EngFlow/gazelle_cc#76]
Running gazelle with the proto,cc,go languages creates a proto_library and a cc_proto_library rules on the first run. A second run deletes the cc_proto_library target. Am I holding this wrong or is there an issue with the existing targets in the BUILD file?

Here is a repro PR where running //:gazelle deletes the cc_proto_library: https://github.com/satreix/everest/pull/1140

**Comment by WojciechMazur** [comment]
Hey, thank you for reporting the issue. Which version of the gazelle were you using? I think it was fixed already in https://github.com/EngFlow/gazelle_cc/pull/56

**Comment by satreix** [comment]
Hi. 

Versions, as per the reproducer:

- gazelle@0.44.0
- gazelle_cc@17c478bfef53ced060b191d647437ef067052f67

IIUC #80 does not solve the issue. It does not remove the `cc_proto_library` anymore, but if I remove them manually it does not add them back either.

**Comment by WojciechMazur** [comment]
The issue with rules not being generated seems to be related to the fact that gazelle infers the `proto.Mode` in https://github.com/bazel-contrib/bazel-gazelle/blob/70f6c6ed7b9af4956e92fccf20f3cac1454ba2a4/language/proto/config.go#L236-L283 
It can find `proto_cc_library` load and changes the mode to `Disable` which in result terminates the notifications about proto_library being defined. I belive the `rules_jvm` might have the same issue - they also consume only `args.OtherGen` which at this point would not contain any `proto_library` 

I'm working on fixing the issue in upstream gazelle

**Comment by satreix** [comment]
Verified as fixed. Thanks @WojciechMazur !
